apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig


metadata:
 name: hhld-stockBroker-cluster
 region: us-east-1


nodeGroups:
 - name: hhld-nodes
   instanceType: t2.micro
   desiredCapacity: 2
   ssh:
     allow: true


fargateProfiles:
 - name: default
   selectors:
     - namespace: default