apiVersion: apps/v1
kind: Deployment
metadata:
 name: hhld-stock-broker-watchlist
 labels:
   app: hhld-stock-broker-watchlist
spec:
 replicas: 1 # You can adjust the number of replicas as needed
 selector:
   matchLabels:
     app: hhld-stock-broker-watchlist
 template:
   metadata:
     labels:
       app: hhld-stock-broker-watchlist
   spec:
     containers:
       - name: watchlist
         image: 448049807984.dkr.ecr.us-east-1.amazonaws.com/kathir-ecr-repo:watchlist
         ports:
           - containerPort: 8084 # Assuming your client application runs on port 3000
         envFrom: # Add this section to inject environment variables from ConfigMap
           - configMapRef:
               name: wl-env-config # Name of your ConfigMap